package cmd

import (
	"p2p-tun/auth"
	"p2p-tun/cmd/context"
	"p2p-tun/host"

	logging "github.com/ipfs/go-log/v2"
	"github.com/libp2p/go-libp2p-core/crypto"
	"github.com/urfave/cli/v2"
)

var (
	log = logging.Logger("p2p-tun")
)

var Flags = []cli.Flag{
	&cli.StringFlag{
		Name:    "private-key",
		Usage:   "private key generated by genkey cmd",
		EnvVars: []string{"PRIVATE_KEY"},
	},
	&cli.IntFlag{
		Name:  "listen-port",
		Usage: "p2p listen port",
		Value: 0,
	},
	&cli.StringFlag{
		Name:    "secret",
		Usage:   "authenticate user",
		Value:   "",
		EnvVars: []string{"SECRET"},
	},
	&cli.BoolFlag{
		Name:  "debug",
		Usage: "log debug",
	},
}

var Commands = []*cli.Command{
	ClientCmd(),
	ServerCmd(),
	GenkeyCmd(),
}

func common(c *cli.Context) error {
	privKeyStr := c.String("private-key")
	var privKey crypto.PrivKey
	var err error
	if len(privKeyStr) == 0 {
		privKey, err = genkey()
	} else {
		b, err := crypto.ConfigDecodeKey(privKeyStr)
		if err != nil {
			return err
		}
		privKey, err = crypto.UnmarshalPrivateKey(b)
	}

	if err != nil {
		return err
	}

	conf := &host.NodeConfig{
		PrivateKey: privKey,
		ListenPort: c.Int("listen-port"),
	}

	secret := c.String("secret")
	if len(secret) > 0 {
		conf.Auth = auth.NewAuthenticator(secret)
	}

	logLevel := "info"
	if c.Bool("debug") {
		logLevel = "debug"
	}
	logging.SetLogLevel("p2p-tun", logLevel)

	c.Context = context.SetLogger(c.Context, log)
	c.Context = context.SetNodeConfig(c.Context, conf)

	return nil
}
